name = input('What is your name?')
age = input ('How old are you?')
city = input('Where do you live?')
print('Hello,', str.title(name))
print('Your age is', (age))
print('You live in', str.title(city))
print(name, age, city)